# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contionus Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: holly_ways_test
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate:test
        npm run test
      env:
        CI: true
        HOST: http://localhost
        PORT: 5000
        ENDPOINT_FILE: /file
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSSWORD: password
        DB_NAME: holly_ways_test
        DB_PORT:  32574
        DB_DIALECT: mysql
        DBTEST_HOST: 127.0.0.1
        DBTEST_USER: root
        DBTEST_PASSSWORD: password
        DBTEST_NAME: holly_ways_test
        DBTEST_PORT: 32574
        DBTEST_DIALECT: mysql
        TOKENKEY: ${{ secrets.TOKENKEY }}
