# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contionus Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine3.15
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: holly_ways_test
        ports:
        - 32574:5432
        
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate:test
        npm run test
      env:
        CI: true
        HOST: http://localhost
        PORT: 5000
        ENDPOINT_FILE: /file
        DB_HOST: 127.0.0.1
        DB_USER: developer
        DB_PASSSWORD: developer
        DB_NAME: holly_ways_test
        DB_PORT:  32574
        DB_DIALECT: postgres
        DBTEST_HOST: 127.0.0.1
        DBTEST_USER: developer
        DBTEST_PASSSWORD: developer
        DBTEST_NAME: holly_ways_test
        DBTEST_PORT: 32574
        DBTEST_DIALECT: postgres
        TOKENKEY: ${{ secrets.TOKENKEY }}
